### ISSUE TITLE
Sparky; Karma Reminder

### ISSUE THREAD

**Issue by aliyss** [cf-official/Sparky-Legacy-.Net#13]
Take messages like [thanks, thank you, etc.] and check if the user has reacted with a thumbs-up reaction within the coming 5 minutes. If not send them a reminder to the user, that they have the possibility to react.

**Comment by ghost** [comment]
i think this idea has good potential, but should also check for more "thank you" style messages in the coming five minutes from the same person before reminding them, if they say thank you again then they are still getting help and the timer should be reset.

**Comment by trinitrotoluene** [comment]
Interesting idea, and I definitely see the use-case. 

What kind of form do you imagine these reminders taking?
